version: '3.3'

services:
  {DOMAIN_NAME}:
    image: nginx
    volumes:
      - ./wordpress:/var/www/html:ro
      - ./nginx:/etc/nginx/conf.d:rw
    networks:
      - web
      - local
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.{DOMAIN_NAME}.entrypoints=web,websecure"
        - "traefik.http.routers.{DOMAIN_NAME}.rule=Host(`{DOMAIN_URL}`)"
        - "traefik.http.services.{DOMAIN_NAME}.loadbalancer.server.port=80"
        - "traefik.port=80"


networks:
  web:
    external:
      name: web
  local:
    external:
      name: local